# This file was generated by GoReleaser. DO NOT EDIT.
cask "wa-cli" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "bdab9eb702323a0bc16a4e4fcc1808dfeeb1185e0ffcf20dbb6f2b277fbbdff4"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef1d1434b7b68809a6a817954af7c66fa34daae580da5a90b3f08ca8895108c2"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6892609e1028250a35be553bd6b1b99f1c7e267844292f6a69a6882389cb6fc"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "42fe8082b4c30033d55e0bbfd4716b2af499f1c4b0bf3b6286cb192163b9a341"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wa-cli"
  desc "A WhatsApp client for your terminal, built on whatsmeow"
  homepage "https://github.com/codebyoketch/wa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wa"

  # No zap stanza required

end
