# This file was generated by GoReleaser. DO NOT EDIT.
cask "wa-cli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "0ec93d922afe9008459cbced080de4a277e9b4631fdff92cd74795d47ad3ffdf"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb155393739e710caa96a469ea67020395682b58e95d54adfff09831ed3f6a08"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c36207d83d7b4ac7b0ad8a4a929d6572764b6abbd572b6ee7d304eed22274237"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cae1948134a496583de22c12dab4e3ef0d785c0633924dc7e5df46317303f75f"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wa-cli"
  desc "A WhatsApp client for your terminal, built on whatsmeow"
  homepage "https://github.com/codebyoketch/wa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wa"

  # No zap stanza required

end
