# This file was generated by GoReleaser. DO NOT EDIT.
cask "wa-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "1c8549df17f3e3669806df5758b851a478844fbae0f502e5480fa890efe33dae"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a4cf1d20c64b98a3d2ddc195af53c464ec83afa66ba789b37984b4e2487a6f6"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a8988b77b5ad153baec9d6ceacd3a7763612c417a45ae03f77ab749b8ea8708"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "811d5c679be87b74947b88fc106e5f2aa45aa0f8d93b61eaa1a741c9c88443ec"
      url "https://github.com/codebyoketch/wa-cli/releases/download/v#{version}/wa-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wa-cli"
  desc "A WhatsApp client for your terminal, built on whatsmeow"
  homepage "https://github.com/codebyoketch/wa-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wa-cli"

  # No zap stanza required

end
